# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f813d85b24842a6c0624e2d7b6b164193437d9c547f0590c18f2423ba21cea082d7099e242e6d47256f5e118bec6cb876df228c36261a57f9f4269bc26fda2e4

test:
  secret_key_base: a2ef4260756a7aa4f91287756a8bb1dd046f83bef2ab1fc505318c230b9bb5c51dfcdaff43b7a1280ac8c8d3d95c3d66570b2b2cb8ee7dcaf9737aaec17d6a9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
